image: atlassian/default-image:3

pipelines:
  branches:
    '*':
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --bare git@bitbucket.org:cedrickylo/nodalai-genwebapp.git
            - cd nodalai-genwebapp.git
            - git push --mirror git@github.com:Cedrickylo/nodalai-genwebapp.git