export const constants = {
    DB_NAME: 'AIQuizGeneratorDB_v4',
    CLOUD_SYNC_KEY: 'puter_quiz_sync_v4',
    IN_PROGRESS_QUIZ_KEY: 'AIQuizInProgress',
    MAX_GENERATION_ATTEMPTS: 5,
    MAX_GENERATIONS_PER_WINDOW: 10,
    GENERATION_WINDOW_MS: 3 * 60 * 60 * 1000,
    SHORT_TERM_COOLDOWN_MS: 3 * 60 * 1000,
    SHORT_TERM_MAX_GENERATIONS: 2,
    GENERATION_LOG_LOCAL_KEY: 'AIQuizGenerationLog',
    GENERATION_LOG_CLOUD_KEY: 'AIQuizGenerationLog_v1',
    MIN_QUIZ_QUESTIONS: 5,
    MAX_QUIZ_QUESTIONS: 100,
    WELCOME_DISMISSED_KEY: 'nodal_welcome_dismissed_v1', // Cleaned up duplicate
    QUIZ_ATTEMPTS_DB_KEY: 'nodal_quiz_takes_v1',
    OFFLINE_DOWNLOADS_DB_KEY: 'nodal_offline_downloads_v1',
    OFFLINE_EXPIRATION_MS: 7 * 24 * 60 * 60 * 1000,
    STORAGE_ENCRYPTION_KEY: 'NodalAI_Secure_Quiz_Storage_2026_@cedrickylo',
    STORAGE_ENC_PREFIX: 'NODAL_ENC_v1:'
};

export const elements = {
    views: {
        start: document.getElementById('start-view'),
        loading: document.getElementById('loading-view'),
        quiz: document.getElementById('quiz-view'),
        results: document.getElementById('results-view'),
        'history-fullscreen': document.getElementById('history-fullscreen-view'),
        help: document.getElementById('help-view'),
        about: document.getElementById('about-view'),
        account: document.getElementById('account-view'),
        statistics: document.getElementById('statistics-view'),
        review: document.getElementById('review-view'),
        downloads: document.getElementById('downloads-view'),
        'whats-new': document.getElementById('whats-new-view')
    },
    account: document.getElementById('account-view'),
    globalSyncDone: document.getElementById('sync-icon-done'),
    globalSyncLoad: document.getElementById('sync-icon-loading'),
    quizSyncDone: document.querySelector('#quiz-sync-indicator .sync-icon-done'),
    quizSyncLoad: document.querySelector('#quiz-sync-indicator .sync-icon-loading'),
    fileUploadInput: document.getElementById('file-upload-input'),
    addMoreFilesInput: document.getElementById('add-more-files-input'),
    selectedFilesContainer: document.getElementById('selected-files-container'),
    selectedFilesList: document.getElementById('selected-files-list'),
    clearFilesBtn: document.getElementById('clear-files-btn'),
    importQuizInput: document.getElementById('import-quiz-input'),
    openImportChoiceBtn: document.getElementById('open-import-choice-btn'),
    importChoiceModal: document.getElementById('import-choice-modal'),
    closeImportChoiceModalBtn: document.getElementById('close-import-choice-modal-btn'),
    closeImportChoiceFooterBtn: document.getElementById('close-import-choice-footer-btn'),
    importChoiceFileBtn: document.getElementById('import-choice-file-btn'),
    importChoicePasteBtn: document.getElementById('import-choice-paste-btn'),
    openPasteJsonBtn: document.getElementById('open-paste-json-btn'),
    pasteJsonModal: document.getElementById('paste-json-modal'),
    closePasteJsonModalBtn: document.getElementById('close-paste-json-modal-btn'),
    cancelPasteJsonBtn: document.getElementById('cancel-paste-json-btn'),
    submitPasteJsonBtn: document.getElementById('submit-paste-json-btn'),
    pasteJsonTextarea: document.getElementById('paste-json-textarea'),
    aiPromptPasteBtn: document.getElementById('ai-prompt-paste-btn'),
    fileNameDisplay: document.getElementById('file-name'),
    generateQuizBtn: document.getElementById('generate-quiz-btn'),
    statusMessage: document.getElementById('status-message'),
    loadingMessage: document.getElementById('loading-message'),
    loadingTitle: document.getElementById('loading-title'),
    loadingSummaryBadges: document.getElementById('loading-summary-badges'),
    loadingProgressBar: document.getElementById('loading-progress-bar'),
    loadingProgressPercent: document.getElementById('loading-progress-percent'),
    loadingProgressStageText: document.getElementById('loading-progress-stage-text'),
    loadingTimeElapsed: document.getElementById('loading-time-elapsed'),
    loadingTimeEstimated: document.getElementById('loading-time-estimated'),
    loadingDelayContainer: document.getElementById('loading-delay-container'),
    loadingCancelCopyBtn: document.getElementById('loading-cancel-copy-btn'),
    loadingCancelBtn: document.getElementById('loading-cancel-btn'),
    questionCountInput: document.getElementById('question-count'),
    difficultyRadios: document.querySelectorAll('input[name="difficulty"]'),
    customOptionsDiv: document.getElementById('custom-options'),
    customQuestionTypeSelect: document.getElementById('custom-question-type'),
    customMixedCountsDiv: document.getElementById('custom-mixed-counts'),
    customCountInputs: document.querySelectorAll('.custom-count'),
    customTotalFeedback: document.getElementById('custom-total-feedback'),
    timeLimitToggle: document.getElementById('time-limit-toggle'),
    timeLimitOptions: document.getElementById('time-limit-options'),
    timePresetRadios: document.querySelectorAll('input[name="time_preset"]'),
    customTimeInputContainer: document.getElementById('custom-time-input-container'),
    customTimeLimitInput: document.getElementById('custom-time-limit-input'),
    timerTotalDisplayEl: document.getElementById('timer-total-display'),
    timerDisplayEl: document.getElementById('timer-display'),
    visualTimerContainer: document.getElementById('visual-timer-container'),
    visualTimerBar: document.getElementById('visual-timer-bar'),
    attemptLimitToggle: document.getElementById('attempt-limit-toggle'),
    attemptLimitOptions: document.getElementById('attempt-limit-options'),
    attemptLimitInput: document.getElementById('attempt-limit-input'),
    attemptDisplayEl: document.getElementById('attempt-display'),
    summaryOnlyToggle: document.getElementById('summary-only-toggle'),
    nextQuestionBtn: document.getElementById('next-question-btn'),
    skipQuestionBtn: document.getElementById('skip-question-btn'),
    restartQuizBtn: document.getElementById('restart-quiz-btn'),
    reviewQuizBtn: document.getElementById('review-quiz-btn'),
    exportQuizBtn: document.getElementById('export-quiz-btn'),
    homeBtn: document.getElementById('home-btn'),
    saveQuizBtn: document.getElementById('save-quiz-btn'),
    muteSoundBtn: document.getElementById('mute-sound-btn'),
    progressEl: document.getElementById('progress'),
    scoreEl: document.getElementById('score'),
    questionTextEl: document.getElementById('question-text'),
    answerAreaEl: document.getElementById('answer-area'),
    explanationAreaEl: document.getElementById('explanation-area'),
    historyList: document.getElementById('history-list'),
    historySkeleton: document.getElementById('history-skeleton'),
    showAllHistoryBtn: document.getElementById('show-all-history-btn'),
    historyFullscreenView: document.getElementById('history-fullscreen-view'),
    historyFullscreenBackBtn: document.getElementById('history-fullscreen-back-btn'),
    fullHistorySyncBtn: document.getElementById('full-history-sync-btn'),
    historyFullList: document.getElementById('history-full-list'),
    helpBackBtn: document.getElementById('help-back-btn'),
    aboutBackBtn: document.getElementById('about-back-btn'),
    openWhatsNewBtn: document.getElementById('open-whats-new-btn'),
    whatsNewBackBtn: document.getElementById('whats-new-back-btn'),
    whatsNewBreadcrumbs: document.getElementById('whats-new-breadcrumbs'),
    whatsNewCrumbHelp: document.getElementById('whats-new-crumb-help'),
    openMigrationBtn: document.getElementById('open-migration-btn'),
    openMigrationLoggedOutBtn: document.getElementById('open-migration-logged-out-btn'),
    migrationModal: document.getElementById('migration-modal'),
    migrationModalBackBtn: document.getElementById('migration-modal-back-btn'),
    closeMigrationModalBtn: document.getElementById('close-migration-modal-btn'),
    migrationChoiceExportBtn: document.getElementById('migration-choice-export-btn'),
    migrationChoiceImportBtn: document.getElementById('migration-choice-import-btn'),
    startExportBtn: document.getElementById('start-export-btn'),
    startImportBtn: document.getElementById('start-import-btn'),
    migrationFileInput: document.getElementById('migration-file-input'),
    selectImportFileBtn: document.getElementById('select-import-file-btn'),
    migrationDropZone: document.getElementById('migration-drop-zone'),
    migrationImportSkeleton: document.getElementById('migration-import-skeleton'),
    migrationImportSummary: document.getElementById('migration-import-summary'),
    importPickDifferentBtn: document.getElementById('import-pick-different-btn'),
    migrationProgressDoneBtn: document.getElementById('migration-progress-done-btn'),
    migrationErrorModal: document.getElementById('migration-error-modal'),
    migrationErrorCloseBtn: document.getElementById('migration-error-close-btn'),
    mobileNavHomeBtn: document.getElementById('mobile-nav-home-btn'),
    mobileNavHistoryBtn: document.getElementById('mobile-nav-history-btn'),
    mobileNavMenuBtn: document.getElementById('mobile-nav-menu-btn'),
    mobileMenuModal: document.getElementById('mobile-menu-modal'),
    mobileMenuCloseBtn: document.getElementById('mobile-menu-close-btn'),
    mobileMenuDownloadsBtn: document.getElementById('mobile-menu-downloads-btn'),
    mobileMenuHelpBtn: document.getElementById('mobile-menu-help-btn'),
    mobileMenuAboutBtn: document.getElementById('mobile-menu-about-btn'),
    mobileMenuAccountBtn: document.getElementById('mobile-menu-account-btn'),
    mobileMenuInstallBtn: document.getElementById('mobile-menu-install-btn'),
    mobileMenuBackdrop: document.getElementById('mobile-menu-backdrop'),
    desktopNavHomeBtn: document.getElementById('desktop-nav-home-btn'),
    desktopNavHistoryBtn: document.getElementById('desktop-nav-history-btn'),
    desktopNavDownloadsBtn: document.getElementById('desktop-nav-downloads-btn'),
    desktopNavHelpBtn: document.getElementById('desktop-nav-help-btn'),
    desktopNavAboutBtn: document.getElementById('desktop-nav-about-btn'),
    desktopNavAccountBtn: document.getElementById('desktop-nav-account-btn'),
    desktopNavInstallBtn: document.getElementById('desktop-nav-install-btn'),
    syncCloudBtn: document.getElementById('sync-cloud-btn'),
    resumeQuizBtn: document.getElementById('resume-quiz-btn'),
    toastEl: document.getElementById('toast-notification'),
    toastMessageEl: document.getElementById('toast-message'),
    loadingOverlay: document.getElementById('loading-overlay'),
    loadingOverlayTitle: document.getElementById('loading-overlay-title'),
    loadingOverlayMessage: document.getElementById('loading-overlay-message'),
    startSubtitle: document.getElementById('start-subtitle'),
    fileActionsDiv: document.getElementById('file-actions'),
    saveCustomizeBtn: document.getElementById('save-customize-btn'),
    cancelCustomizeBtn: document.getElementById('cancel-customize-btn'),
    questionCountGroup: document.getElementById('question-count-group'),
    difficultyGroup: document.getElementById('difficulty-group'),
    customTypeGroup: document.getElementById('custom-type-group'),
    renameContainer: document.getElementById('rename-container'),
    editQuizNameInput: document.getElementById('edit-quiz-name'),
    customizeSection: document.getElementById('customize-section'),
    customizeToggleBtn: document.getElementById('customize-toggle-btn'),
    deleteCustomizeBtn: document.getElementById('delete-customize-btn'),
    customizeContent: document.getElementById('customize-content'),
    customizeToggleIcon: document.getElementById('customize-toggle-icon'),
    resultsActions: document.getElementById('results-actions'),
    createRemedialBtn: document.getElementById('create-remedial-btn'),
    remedialSetupModal: document.getElementById('remedial-setup-modal'),
    closeRemedialSetupModalBtn: document.getElementById('close-remedial-setup-modal-btn'),
    cancelRemedialBtn: document.getElementById('cancel-remedial-btn'),
    generateRemedialQuizBtn: document.getElementById('generate-remedial-quiz-btn'),
    remedialQuizNameInput: document.getElementById('remedial-quiz-name'),
    remedialQuestionCountInput: document.getElementById('remedial-question-count'),
    remedialDifficultyRadios: document.querySelectorAll('input[name="remedial_difficulty"]'),
    remedialCustomOptionsDiv: document.getElementById('remedial-custom-options'),
    remedialCustomQuestionTypeSelect: document.getElementById('remedial-custom-question-type'),
    remedialCustomMixedCountsDiv: document.getElementById('remedial-custom-mixed-counts'),
    remedialCustomCountInputs: document.querySelectorAll('.remedial-custom-count'),
    remedialCustomTotalFeedback: document.getElementById('remedial-custom-total-feedback'),
    remedialTimeLimitToggle: document.getElementById('remedial-time-limit-toggle'),
    remedialTimeLimitOptions: document.getElementById('remedial-time-limit-options'),
    remedialTimerModeSelect: document.getElementById('remedial-timer-mode-select'),
    remedialQuizTimePresetsContainer: document.getElementById('remedial-quiz-time-presets-container'),
    remedialQuestionTimeContainer: document.getElementById('remedial-question-time-container'),
    remedialQuestionTimeInput: document.getElementById('remedial-question-time-input'),
    remedialTimePresetRadios: document.querySelectorAll('input[name="remedial_time_preset"]'),
    remedialCustomTimeInputContainer: document.getElementById('remedial-custom-time-input-container'),
    remedialCustomTimeLimitInput: document.getElementById('remedial-custom-time-limit-input'),
    remedialAttemptLimitToggle: document.getElementById('remedial-attempt-limit-toggle'),
    remedialAttemptLimitOptions: document.getElementById('remedial-attempt-limit-options'),
    remedialAttemptLimitInput: document.getElementById('remedial-attempt-limit-input'),
    remedialSummaryOnlyToggle: document.getElementById('remedial-summary-only-toggle'),
    remedialSecondChanceToggle: document.getElementById('remedial-second-chance-toggle'),
    remedialSecondChanceOptions: document.getElementById('remedial-second-chance-options'),
    remedialMaxChancesInput: document.getElementById('remedial-max-chances-input'),
    remedialAllowChangeToggle: document.getElementById('remedial-allow-change-toggle'),
    remedialAllowChangeContainer: document.getElementById('remedial-allow-change-container'),
    remedialShuffleQuestionsToggle: document.getElementById('remedial-shuffle-questions-toggle'),
    remedialShuffleChoicesToggle: document.getElementById('remedial-shuffle-choices-toggle'),
    remedialUiModeModern: document.getElementById('remedial-ui-mode-modern'),
    remedialUiModeClassic: document.getElementById('remedial-ui-mode-classic'),
    authBtn: document.getElementById('puter-auth-btn'),
    authBtnText: document.getElementById('auth-btn-text'),
    accountModalOverlay: document.getElementById('account-modal-overlay'),
    accountViewContainer: document.getElementById('account-view-container'),
    accountCard: document.getElementById('account-card'),
    closeAccountBtn: document.getElementById('close-account-btn'),
    modalUsername: document.getElementById('modal-username'),
    modalAccountId: document.getElementById('modal-account-id'),
    modalEmail: document.getElementById('modal-email'),
    modalCreditPanel: document.getElementById('modal-credit-panel'),
    modalCredits: document.getElementById('modal-credits'),
    creditProgress: document.getElementById('credit-progress'),
    buyCreditsBtn: document.getElementById('buy-credits-btn'),
    modalStoragePanel: document.getElementById('modal-storage-panel'),
    modalStorageLabel: document.getElementById('modal-storage-label'),
    modalCooldownPanel: document.getElementById('modal-cooldown-panel'),
    modalCooldownStatus: document.getElementById('modal-cooldown-status'),
    modalCooldownDetail: document.getElementById('modal-cooldown-detail'),
    displayNameInput: document.getElementById('display-name-input'),
    saveDisplayNameBtn: document.getElementById('save-display-name-btn'),
    logoutBtn: document.getElementById('logout-btn'),
    deleteProfileBtn: document.getElementById('delete-profile-btn'),
    deleteProfileLoggedOutBtn: document.getElementById('delete-profile-logged-out-btn'),
    confirmModal: document.getElementById('custom-confirm-modal'),
    confirmTitle: document.getElementById('confirm-title'),
    confirmMessage: document.getElementById('confirm-message'),
    confirmInputContainer: document.getElementById('confirm-input-container'),
    confirmInputLabel: document.getElementById('confirm-input-label'),
    confirmInput: document.getElementById('confirm-input'),
    acceptConfirmBtn: document.getElementById('accept-confirm-btn'),
    cancelConfirmBtn: document.getElementById('cancel-confirm-btn'),
    shareModal: document.getElementById('share-modal'),
    shareBackBtn: document.getElementById('share-back-btn'),
    closeShareModalBtn: document.getElementById('close-share-modal-btn'),
    shareStepMenu: document.getElementById('share-step-menu'),
    shareStepConfig: document.getElementById('share-step-config'),
    shareStepManage: document.getElementById('share-step-manage'),
    shareMenuLinkBtn: document.getElementById('share-menu-link-btn'),
    shareMenuExportBtn: document.getElementById('share-menu-export-btn'),
    shareExpirySelect: document.getElementById('share-expiry-select'),
    generateShareLinkBtn: document.getElementById('generate-share-link-btn'),
    shareLinkInput: document.getElementById('share-link-input'),
    shareLinkTypeBadge: document.getElementById('share-link-type-badge'),
    shareLinkTypeText: document.getElementById('share-link-type-text'),
    toggleShareLinkFormatBtn: document.getElementById('toggle-share-link-format-btn'),
    copyShareLinkBtn: document.getElementById('copy-share-link-btn'),
    disableShareBtn: document.getElementById('disable-share-btn'),
    shareExpiryDisplay: document.getElementById('share-expiry-display'),
    clearFilesBtn: document.getElementById('clear-files-btn'),
    accountLoggedInContent: document.getElementById('account-logged-in-content'),
    accountLoggedOutContent: document.getElementById('account-logged-out-content'),
    accountLoginBtn: document.getElementById('account-login-btn'),
    // FIXED: Changed 'welcomemodal' to match camelCase 'welcomeModal' in helpers.js
    welcomemodal: document.getElementById('welcome-modal-overlay'),    
    welcomeCloseBtn: document.getElementById('welcome-close-btn'),    
    welcomeCheckbox: document.getElementById('welcome-dont-show-again'),
    // --- ADVANCED FEATURE CONTROLS ---
    timerModeSelect: document.getElementById('timer-mode-select'),
    questionTimeInput: document.getElementById('question-time-input'),
    secondChanceToggle: document.getElementById('second-chance-toggle'),
    maxChancesInput: document.getElementById('max-chances-input'),
    shuffleQuestionsToggle: document.getElementById('shuffle-questions-toggle'),
    shuffleChoicesToggle: document.getElementById('shuffle-choices-toggle'),
    revealAnswerBtn: document.getElementById('reveal-answer-btn'),
    allowchangetoggle: document.getElementById('allow-change-toggle'),
    allowChangeToggle: document.getElementById('allow-change-toggle'),
    allowChangeContainer: document.getElementById('allow-change-container'),
    tfCountInput: document.getElementById('tf-count'),
    remedialTfCountInput: document.getElementById('remedial-tf-count'),
    aiChoiceModal: document.getElementById('ai-choice-modal'),
    closeAiChoiceModalBtn: document.getElementById('close-ai-choice-modal-btn'),
    closeAiChoiceFooterBtn: document.getElementById('close-ai-choice-footer-btn'),
    aiChoiceNodalBtn: document.getElementById('ai-choice-nodal-btn'),
    aiChoiceOtherBtn: document.getElementById('ai-choice-other-btn'),
    aiChoiceSummaryBadges: document.getElementById('ai-choice-summary-badges'),
    aiPromptModal: document.getElementById('ai-prompt-modal'),
    closeAiPromptModalBtn: document.getElementById('close-ai-prompt-modal-btn'),
    closeAiPromptFooterBtn: document.getElementById('close-ai-prompt-footer-btn'),
    copyAiPromptBtn: document.getElementById('copy-ai-prompt-btn'),
    copyAiPromptBtnText: document.getElementById('copy-ai-prompt-btn-text'),
    aiPromptTextarea: document.getElementById('ai-prompt-textarea'),
    aiPromptImportBtn: document.getElementById('ai-prompt-import-btn'),
    aiPromptSummaryBadges: document.getElementById('ai-prompt-summary-badges'),
    aiServiceNotice: document.getElementById('ai-service-notice'),
    prevQuestionBtn: document.getElementById('prev-question-btn'),
    nextUnansweredBtn: document.getElementById('next-unanswered-btn'),
    unansweredModal: document.getElementById('unanswered-modal'),
    unansweredCountText: document.getElementById('unanswered-count-text'),
    unansweredNumbersList: document.getElementById('unanswered-numbers-list'),
    unansweredProceedSubmitBtn: document.getElementById('unanswered-proceed-submit-btn'),
    unansweredReviewBtn: document.getElementById('unanswered-review-btn'),
    uiModeRadios: document.querySelectorAll('input[name="ui_mode"]'),
    historySection: document.getElementById('history-section'),
    classicProgressContainer: document.getElementById('classic-progress-container'),
    modernMetaContainer: document.getElementById('modern-meta-container'),
    modernQuestionNumber: document.getElementById('modern-question-number'),
    modernQuestionTypeBadge: document.getElementById('modern-question-type-badge'),
    modernQuestionTypeBadgeDesktop: document.getElementById('modern-question-type-badge-desktop'),
    modernScoreStats: document.getElementById('modern-score-stats'),
    modernStatCorrectCount: document.getElementById('modern-stat-correct-count'),
    modernStatWrongCount: document.getElementById('modern-stat-wrong-count'),
    // Startup & Loading Overlay
    appInitLoader: document.getElementById('app-init-loader'),
    loadingOverlay: document.getElementById('loading-overlay'),
    loadingOverlayTitle: document.getElementById('loading-overlay-title'),
    loadingOverlayMessage: document.getElementById('loading-overlay-message'),
    // Mobile History Actions Submenu
    historyActionsModal: document.getElementById('history-actions-modal'),
    historyActionsBackdrop: document.getElementById('history-actions-backdrop'),
    historyActionsCloseBtn: document.getElementById('history-actions-close-btn'),
    historyActionsCancelBtn: document.getElementById('history-actions-cancel-btn'),
    historySubmenuQuizTitle: document.getElementById('history-submenu-quiz-title'),
    historySubmenuShareBtn: document.getElementById('history-submenu-share-btn'),
    historySubmenuEditBtn: document.getElementById('history-submenu-edit-btn'),
    historySubmenuDeleteBtn: document.getElementById('history-submenu-delete-btn'),
    // Shared Quiz Received Action Modal
    sharedQuizModal: document.getElementById('shared-quiz-modal'),
    sharedQuizTitle: document.getElementById('shared-quiz-title'),
    sharedQuizSubheading: document.getElementById('shared-quiz-subheading'),
    sharedQuizBadge: document.getElementById('shared-quiz-badge'),
    sharedQuizMeta: document.getElementById('shared-quiz-meta'),
    sharedQuizStartBtn: document.getElementById('shared-quiz-start-btn'),
    sharedQuizStartText: document.getElementById('shared-quiz-start-text'),
    sharedQuizCustomizeBtn: document.getElementById('shared-quiz-customize-btn'),
    sharedQuizSaveBtn: document.getElementById('shared-quiz-save-btn'),
    sharedQuizSaveText: document.getElementById('shared-quiz-save-text'),
    sharedQuizCloseBtn: document.getElementById('shared-quiz-close-btn'),
    // Statistics & Review Elements
    statisticsView: document.getElementById('statistics-view'),
    statisticsBackBtn: document.getElementById('statistics-back-btn'),
    statisticsTitle: document.getElementById('statistics-title'),
    statisticsSyncBtn: document.getElementById('statistics-sync-btn'),
    statisticsBreadcrumbs: document.getElementById('statistics-breadcrumbs'),
    statsCrumbHistory: document.getElementById('stats-crumb-history'),
    statisticsSummary: document.getElementById('statistics-summary'),
    statisticsTakeCountBadge: document.getElementById('statistics-take-count-badge'),
    statisticsTakesContainer: document.getElementById('statistics-takes-container'),
    statisticsTakesList: document.getElementById('statistics-takes-list'),
    statisticsOfflineBar: document.getElementById('statistics-offline-bar'),
    statisticsOfflineStatusText: document.getElementById('statistics-offline-status-text'),
    statisticsOfflineSubtext: document.getElementById('statistics-offline-subtext'),
    statisticsOfflineManageBtn: document.getElementById('statistics-offline-manage-btn'),
    
    reviewView: document.getElementById('review-view'),
    reviewBackBtn: document.getElementById('review-back-btn'),
    reviewTitle: document.getElementById('review-title'),
    reviewBreadcrumbs: document.getElementById('review-breadcrumbs'),
    reviewCrumbHistory: document.getElementById('review-crumb-history'),
    reviewCrumbStats: document.getElementById('review-crumb-stats'),
    reviewTakeSummaryBanner: document.getElementById('review-take-summary-banner'),
    reviewQuestionsContainer: document.getElementById('review-questions-container'),
    reviewQuizBtn: document.getElementById('review-quiz-btn'),
    historySubmenuStatsBtn: document.getElementById('history-submenu-stats-btn'),
    
    // Downloads View Elements
    downloadsView: document.getElementById('downloads-view'),
    downloadsBackBtn: document.getElementById('downloads-back-btn'),
    downloadsStorageBadge: document.getElementById('downloads-storage-badge'),
    downloadsList: document.getElementById('downloads-list'),

    // History Submenu Offline Button
    historySubmenuOfflineBtn: document.getElementById('history-submenu-offline-btn'),
    historySubmenuOfflineIconContainer: document.getElementById('history-submenu-offline-icon-container'),
    historySubmenuOfflineIcon: document.getElementById('history-submenu-offline-icon'),
    historySubmenuOfflineText: document.getElementById('history-submenu-offline-text'),
    historySubmenuOfflineSubtext: document.getElementById('history-submenu-offline-subtext'),

    // Offline Modal Elements
    offlineModal: document.getElementById('offline-modal'),
    offlineModalQuizTitle: document.getElementById('offline-modal-quiz-title'),
    offlineModalCloseBtn: document.getElementById('offline-modal-close-btn'),
    offlineModalStatusBadge: document.getElementById('offline-modal-status-badge'),
    offlineModalStorageSize: document.getElementById('offline-modal-storage-size'),
    offlineModalExpiry: document.getElementById('offline-modal-expiry'),
    offlineModalProgressContainer: document.getElementById('offline-modal-progress-container'),
    offlineModalProgressBar: document.getElementById('offline-modal-progress-bar'),
    offlineModalProgressText: document.getElementById('offline-modal-progress-text'),
    offlineModalDownloadBtn: document.getElementById('offline-modal-download-btn'),
    offlineModalRenewBtn: document.getElementById('offline-modal-renew-btn'),
    offlineModalRemoveBtn: document.getElementById('offline-modal-remove-btn'),
    reduceMotionToggle: document.getElementById('reduce-motion-toggle'),
    reduceMotionToggleLoggedOut: document.getElementById('reduce-motion-toggle-logged-out')
};

function getInitialQuizHistory() {
    try {
        const raw = localStorage.getItem(constants.DB_NAME);
        if (!raw) return {};
        const trimmed = raw.trim();
        if (typeof CryptoJS !== 'undefined' && CryptoJS.AES && (trimmed.startsWith('NODAL_ENC_v1:') || trimmed.startsWith('U2FsdGVkX1'))) {
            const ciphertext = trimmed.startsWith('NODAL_ENC_v1:') ? trimmed.slice('NODAL_ENC_v1:'.length) : trimmed;
            const bytes = CryptoJS.AES.decrypt(ciphertext, constants.STORAGE_ENCRYPTION_KEY);
            const str = bytes.toString(CryptoJS.enc.Utf8);
            if (str) return JSON.parse(str);
        }
        return JSON.parse(trimmed);
    } catch (e) {
        console.warn('Failed to parse initial quizHistory:', e);
        return {};
    }
}

export const state = {
    fileContent: '',
    fileHash: '',
    questions: [],
    userAnswers: [],
    score: 0,
    shuffledIndices: [],
    shuffledOptionsMap: {},
    audioContext: null,
    audioToneLoaded: false,
    audioInitialized: false,
    currentQuizConfig: {},
    currentQuizKey: '',
    currentFileName: '',
    aiPromptShowNotice: false,
    correctSound: null,
    incorrectSound: null,
    isMuted: localStorage.getItem('nodal_quiz_muted') === 'true',
    isReduceMotion: localStorage.getItem('nodal_reduce_motion') === 'true',
    isDeviceOrientationLocked: false,
    loadingInterval: null,
    toastTimeout: null,
    quizTimerInterval: null,
    quizHistory: getInitialQuizHistory(),
    generationLog: [],
    savedProgress: null,
    timeRemaining: 0,
    isTimedQuiz: false,
    totalQuizTime: 0,
    currentShuffledIndexPos: 0,
    currentQuestionIndex: 0,
    isReviewingUnanswered: false,
    answeredOriginalIndices: new Set(),
    skippedOriginalIndices: new Set(),
    currentSkippedItemIndex: 0,
    inSkippedRound: false,
    currentSkippedArray: [],
    isAttemptLimited: false,
    maxAttempts: 3,
    currentAttempts: 0,
    isCustomizingHistory: false,
    customizingQuizData: null,
    incorrectQuestionsForRemedial: [],
    initialCustomizeState: {},
    activeShareStep: 'menu',
    currentShareQuizKey: null,
    shareOriginView: 'start',
    shareOriginHash: '#home',
    shareOriginScrollY: null,
    editOriginView: 'start',
    deletedQuizKeys: JSON.parse(localStorage.getItem('nodal_deleted_quiz_keys') || '{}'),
    // --- ADVANCED RUNTIME STATE ---
    currentQuestionTimeRemaining: 0,
    currentQuestionChancesLeft: 0,
    selectedAnswerTemp: null,
    questionTimerInterval: null,
    activeHistoryMenuKey: null,
    pendingSharedQuiz: null,
    historyMenuOriginHash: '#history',
    historyMenuOriginView: 'history-fullscreen',
    historyMenuPreScrollY: null,
    currentStatsQuizKey: null,
    currentReviewTake: null,
    reviewOrigin: 'statistics',
    statisticsOrigin: 'history',
    navRootOrigin: 'home',
    currentCompletedTake: null,
    activeOfflineModalKey: null,
    historyOrigin: 'nav',
    // --- AI GENERATION RUNTIME STATE ---
    aiGenerationAbortController: null,
    aiGenerationInterval: null,
    aiGenerationStartTime: 0,
    aiGenerationEstimatedSec: 0,
    preModalScrollY: null,
    isQuizCompleted: false,
    preQuizHash: '#home'
};