export const constants = {
    DB_NAME: 'AIQuizGeneratorDB_v4',
    CLOUD_SYNC_KEY: 'puter_quiz_sync_v4',
    IN_PROGRESS_QUIZ_KEY: 'AIQuizInProgress',
    MAX_GENERATION_ATTEMPTS: 5
};

export const elements = {
    views: {
        start: document.getElementById('start-view'),
        loading: document.getElementById('loading-view'),
        quiz: document.getElementById('quiz-view'),
        results: document.getElementById('results-view')
    },
    globalSyncDone: document.getElementById('sync-icon-done'),
    globalSyncLoad: document.getElementById('sync-icon-loading'),
    quizSyncDone: document.querySelector('#quiz-sync-indicator .sync-icon-done'),
    quizSyncLoad: document.querySelector('#quiz-sync-indicator .sync-icon-loading'),
    fileUploadInput: document.getElementById('file-upload-input'),
    importQuizInput: document.getElementById('import-quiz-input'),
    fileNameDisplay: document.getElementById('file-name'),
    generateQuizBtn: document.getElementById('generate-quiz-btn'),
    statusMessage: document.getElementById('status-message'),
    loadingMessage: document.getElementById('loading-message'),
    loadingTitle: document.getElementById('loading-title'),
    questionCountInput: document.getElementById('question-count'),
    difficultyRadios: document.querySelectorAll('input[name="difficulty"]'),
    customOptionsDiv: document.getElementById('custom-options'),
    customQuestionTypeSelect: document.getElementById('custom-question-type'),
    customMixedCountsDiv: document.getElementById('custom-mixed-counts'),
    customCountInputs: document.querySelectorAll('.custom-count'),
    customTotalFeedback: document.getElementById('custom-total-feedback'),
    timeLimitToggle: document.getElementById('time-limit-toggle'),
    timeLimitOptions: document.getElementById('time-limit-options'),
    timePresetRadios: document.querySelectorAll('input[name="time_preset"]'),
    customTimeInputContainer: document.getElementById('custom-time-input-container'),
    customTimeLimitInput: document.getElementById('custom-time-limit-input'),
    timerDisplayEl: document.getElementById('timer-display'),
    visualTimerContainer: document.getElementById('visual-timer-container'),
    visualTimerBar: document.getElementById('visual-timer-bar'),
    attemptLimitToggle: document.getElementById('attempt-limit-toggle'),
    attemptLimitOptions: document.getElementById('attempt-limit-options'),
    attemptLimitInput: document.getElementById('attempt-limit-input'),
    attemptDisplayEl: document.getElementById('attempt-display'),
    summaryOnlyToggle: document.getElementById('summary-only-toggle'),
    nextQuestionBtn: document.getElementById('next-question-btn'),
    skipQuestionBtn: document.getElementById('skip-question-btn'),
    restartQuizBtn: document.getElementById('restart-quiz-btn'),
    exportQuizBtn: document.getElementById('export-quiz-btn'),
    homeBtn: document.getElementById('home-btn'),
    saveQuizBtn: document.getElementById('save-quiz-btn'),
    progressEl: document.getElementById('progress'),
    scoreEl: document.getElementById('score'),
    questionTextEl: document.getElementById('question-text'),
    answerAreaEl: document.getElementById('answer-area'),
    explanationAreaEl: document.getElementById('explanation-area'),
    historyList: document.getElementById('history-list'),
    clearHistoryBtn: document.getElementById('clear-history-btn'),
    syncCloudBtn: document.getElementById('sync-cloud-btn'),
    resumeQuizBtn: document.getElementById('resume-quiz-btn'),
    toastEl: document.getElementById('toast-notification'),
    toastMessageEl: document.getElementById('toast-message'),
    startSubtitle: document.getElementById('start-subtitle'),
    fileActionsDiv: document.getElementById('file-actions'),
    cancelCustomizeBtn: document.getElementById('cancel-customize-btn'),
    questionCountGroup: document.getElementById('question-count-group'),
    difficultyGroup: document.getElementById('difficulty-group'),
    customTypeGroup: document.getElementById('custom-type-group'),
    renameContainer: document.getElementById('rename-container'),
    editQuizNameInput: document.getElementById('edit-quiz-name'),
    customizeSection: document.getElementById('customize-section'),
    customizeToggleBtn: document.getElementById('customize-toggle-btn'),
    customizeContent: document.getElementById('customize-content'),
    customizeToggleIcon: document.getElementById('customize-toggle-icon'),
    resultsActions: document.getElementById('results-actions'),
    createRemedialBtn: document.getElementById('create-remedial-btn'),
    remedialOptionsView: document.getElementById('remedial-options-view'),
    cancelRemedialBtn: document.getElementById('cancel-remedial-btn'),
    generateRemedialQuizBtn: document.getElementById('generate-remedial-quiz-btn'),
    remedialQuestionCountInput: document.getElementById('remedial-question-count'),
    remedialDifficultyRadios: document.querySelectorAll('input[name="remedial_difficulty"]'),
    remedialCustomOptionsDiv: document.getElementById('remedial-custom-options'),
    remedialCustomQuestionTypeSelect: document.getElementById('remedial-custom-question-type'),
    remedialCustomMixedCountsDiv: document.getElementById('remedial-custom-mixed-counts'),
    remedialCustomCountInputs: document.querySelectorAll('.remedial-custom-count'),
    remedialCustomTotalFeedback: document.getElementById('remedial-custom-total-feedback'),
    remedialTimeLimitToggle: document.getElementById('remedial-time-limit-toggle'),
    remedialTimeLimitOptions: document.getElementById('remedial-time-limit-options'),
    remedialTimePresetRadios: document.querySelectorAll('input[name="remedial_time_preset"]'),
    remedialCustomTimeInputContainer: document.getElementById('remedial-custom-time-input-container'),
    remedialCustomTimeLimitInput: document.getElementById('remedial-custom-time-limit-input'),
    remedialAttemptLimitToggle: document.getElementById('remedial-attempt-limit-toggle'),
    remedialAttemptLimitOptions: document.getElementById('remedial-attempt-limit-options'),
    remedialAttemptLimitInput: document.getElementById('remedial-attempt-limit-input'),
    authBtn: document.getElementById('puter-auth-btn'),
    authBtnText: document.getElementById('auth-btn-text'),
    accountModal: document.getElementById('account-modal'),
    closeAccountModal: document.getElementById('close-account-modal'),
    modalUsername: document.getElementById('modal-username'),
    modalAccountId: document.getElementById('modal-account-id'),
    modalEmail: document.getElementById('modal-email'),
    modalCredits: document.getElementById('modal-credits'),
    creditProgress: document.getElementById('credit-progress'),
    buyCreditsBtn: document.getElementById('buy-credits-btn'),
    displayNameInput: document.getElementById('display-name-input'),
    saveDisplayNameBtn: document.getElementById('save-display-name-btn'),
    logoutBtn: document.getElementById('logout-btn')
};

export const state = {
    fileContent: '',
    fileHash: '',
    questions: [],
    userAnswers: [],
    score: 0,
    shuffledIndices: [],
    currentQuizConfig: {},
    currentQuizKey: '',
    currentFileName: '',
    correctSound: null,
    incorrectSound: null,
    loadingInterval: null,
    toastTimeout: null,
    quizTimerInterval: null,
    quizHistory: JSON.parse(localStorage.getItem(constants.DB_NAME) || '{}'),
    savedProgress: null,
    timeRemaining: 0,
    isTimedQuiz: false,
    totalQuizTime: 0,
    currentShuffledIndexPos: 0,
    answeredOriginalIndices: new Set(),
    skippedOriginalIndices: new Set(),
    currentSkippedItemIndex: 0,
    inSkippedRound: false,
    currentSkippedArray: [],
    isAttemptLimited: false,
    maxAttempts: 3,
    currentAttempts: 0,
    isCustomizingHistory: false,
    customizingQuizData: null,
    incorrectQuestionsForRemedial: [],
    initialCustomizeState: {}
};
